# Generated by Django 3.1.3 on 2020-11-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='fin',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='horas',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='inicio',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='complete',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('horas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('actividades', models.ManyToManyField(to='main.Actividades')),
            ],
        ),
        migrations.AddField(
            model_name='proyectos',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.instituciones'),
        ),
    ]
