# Generated by Django 3.1.3 on 2020-11-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201124_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='actividades',
            field=models.ManyToManyField(null=True, to='main.Actividades'),
        ),
    ]
