# Generated by Django 3.1.3 on 2020-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201126_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instituciones',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
