# Generated by Django 3.1.3 on 2020-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201126_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituciones',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
