# Generated by Django 3.1.3 on 2020-11-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_instituciones_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
