# Generated by Django 3.1.3 on 2020-11-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_peticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.estudiante'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.proyectos'),
        ),
    ]
